create_clock -period 70.000 -name clock -waveform {0.000 35.000} [get_ports clock]

set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports {address[*]}]
set_output_delay -clock [get_clocks clock] -max -add_delay 30.000 [get_ports {address[*]}]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks clock] -max -add_delay 30.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports sync]
set_output_delay -clock [get_clocks clock] -max -add_delay 30.000 [get_ports sync]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports vector_pull]
set_output_delay -clock [get_clocks clock] -max -add_delay 30.000 [get_ports vector_pull]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports write]
set_output_delay -clock [get_clocks clock] -max -add_delay 30.000 [get_ports write]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports memory_lock]
set_output_delay -clock [get_clocks clock] -max -add_delay 30.000 [get_ports memory_lock]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports incompatible]
set_output_delay -clock [get_clocks clock] -max -add_delay 30.000 [get_ports incompatible]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports {debug1[*]}]
set_output_delay -clock [get_clocks clock] -max -add_delay 20.000 [get_ports {debug1[*]}]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports {debug2[*]}]
set_output_delay -clock [get_clocks clock] -max -add_delay 20.000 [get_ports {debug2[*]}]
set_output_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports {debug3[*]}]
set_output_delay -clock [get_clocks clock] -max -add_delay 20.000 [get_ports {debug3[*]}]

set_input_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks clock] -max -add_delay 3.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports interrupt]
set_input_delay -clock [get_clocks clock] -max -add_delay 3.000 [get_ports interrupt]
set_input_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports nmi]
set_input_delay -clock [get_clocks clock] -max -add_delay 3.000 [get_ports nmi]
set_input_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports ready]
set_input_delay -clock [get_clocks clock] -max -add_delay 3.000 [get_ports ready]
set_input_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports reset]
set_input_delay -clock [get_clocks clock] -max -add_delay 3.000 [get_ports reset]
set_input_delay -clock [get_clocks clock] -min -add_delay 0.000 [get_ports set_overflow]
set_input_delay -clock [get_clocks clock] -max -add_delay 3.000 [get_ports set_overflow]
